baseURL = "https://CookieManano.github.io/"
languageCode = "zh-cn"
title = "我的技术小站"
theme = "PaperMod"
enableEmoji = true
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "📝 所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 2

# 主题样式微调（让博客更好看）
[params]
  env = "production"
  title = "我的个人小站"
  description = "记录所有事情"
  author = "CookieManano"
  # 开启首页显示文章摘要
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  # 首页不显示“友情链接”之类的多余块
  hideFooter = false
